# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: Vault
- name: HUGO_VERSION
  value: 0.53
- name: HUGO_DOWNLOAD_URL
  value: https://github.com/gohugoio/hugo/releases/download/v$(HUGO_VERSION)/hugo_$(HUGO_VERSION)_Linux-64bit.tar.gz
- name: HUGO_TGZ
  value: hugo.tgz
- name: REPO_URL
  value: https://$(GH_NAME):$(GH_TOKEN)@github.com/xuqingfeng/xuqingfeng.github.io.git

steps:
- script: |
    curl -o $(HUGO_TGZ) -L $(HUGO_DOWNLOAD_URL)
    tar xzvf $(HUGO_TGZ)
    sudo mv hugo /usr/local/bin
  displayName: 'Install hugo'

- script: |
    git config --global user.name $(GH_NAME)
    git config --global user.email $(GH_EMAIL)
    git clone $(REPO_URL) /tmp/xyz
    cd /tmp/xyz/src
    git submodule init
    git submodule update
    hugo -d ../
  displayName: 'Clone and build site'

- script: |
    cd /tmp/xyz
    git add .
    git commit -m 'Autocommit from Azure Pipelines'
    git push origin HEAD:master
  displayName: 'Push changes back to Github'

- script: |
    rm -rf /tmp/xyz
  displayName: 'Cleanup'
